## accounts_timelinereport 유저 신고기록 테이블 전처리

In [1]:
from google.cloud import bigquery

PROJECT_ID = "sns-analysis-prj"
DATA_SET = "sns_analysis"

client = bigquery.Client(project=PROJECT_ID)

In [3]:
# 전처리 수행 대상 테이블 호출
sql = f"""
    SELECT * 
    FROM `{PROJECT_ID}.{DATA_SET}.accounts_timelinereport`
"""

# 판다스 데이터프레임으로 변환
df = client.query(sql).to_dataframe()

display(df.head())

/Users/youju/anaconda3/envs/pythonProject/lib/python3.11/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,id,reason,created_at,reported_user_id,user_id,user_question_record_id
0,4794,광고,2023-05-10 14:27:44+00:00,917587,1084275,18272641
1,7168,광고,2023-05-12 14:54:46+00:00,967873,1184397,28992803
2,7169,광고,2023-05-12 14:54:52+00:00,967873,1184397,28992803
3,9998,광고,2023-05-14 16:49:58+00:00,1207784,1214760,46645583
4,10257,광고,2023-05-15 06:08:04+00:00,1250642,1228033,48820574

# 결측치 확인 및 데이터 정보 확인

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       208 non-null    Int64
 1   reason                   208 non-null    str
 2   created_at               208 non-null    datetime64[us, UTC]
 3   reported_user_id         208 non-null    Int64
 4   user_id                  208 non-null    Int64
 5   user_question_record_id  208 non-null    Int64
dtypes: Int64(4), datetime64[us, UTC](1), str(1)
memory usage: 16.9 KB

- 결측x

## 중복값

In [5]:
df.duplicated().sum()

np.int64(0)

- 중복값 0
- 따로 확인해야할 컬럼이 있는 것 같지는 않아서 전체 행 중복값만 확인

## 이상치

In [7]:
df.describe()

                id  reported_user_id         user_id  user_question_record_id
count        208.0             208.0           208.0                    208.0
mean   9786.269231       1132496.875  1159945.668269          49325579.326923
std    5713.767759     169412.066968   180095.938183          33112807.364359
min           28.0          837235.0        834089.0                3920588.0
25%        6123.75         966470.25       967120.25               24611783.5
50%        10095.0         1144432.0       1184397.0               47403268.0
75%       14182.25         1225963.0       1291813.0               71795781.0
max        23108.0         1562736.0       1548002.0              140765885.0

In [6]:
df['reason'].unique()

<ArrowStringArray>
['광고', '선정적이거나 폭력적인 내용', '친구를 비하하거나 조롱하는 어투', '타인을 사칭함', '허위 사실 언급']
Length: 5, dtype: str